export class Immobilisation{
  id:number;
  libelle:string;
  description:string;
  reference:string;
  metrique:string;
  marque:string;
  emplacement1:string;
  emplacement2:string;
  allocation:string;
  etat:string;
  quantite:number;
  is_generique:boolean;
  is_active:boolean;
  created_at:Date;
  reference_unite:string;
  codeBarre:string;
  referenceoperateur:string;
  referencesession:string;
}
